import type { Metadata } from "next";
import { Geist, Geist_Mono,Italiana } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
const italiana = Italiana({
  variable: "--font-italiana",
  subsets: ["latin"],
  weight: "400"
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${italiana.variable} bg-purpleN-800 antialiased text-white`}
      >
        {children}
      </body>
    </html>
  );
}
